<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RoomSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rooms = [
            [
                'name' => 'Overwater Pool Villa',
                'code' => 'x',
                'unit' => 11,
                'bedding' => '1 King',
                'extra_bed' => 0,
                'max_total_occupancy' => 3,
                'max_adult_occupancy' => 2,
                'max_child_occupancy' => 1,
                'base_rate_occupancy' => 2,
                'size' => 100.00,
                'rate_high_season' => 1975.00,
                'rate_low_season' => 1225.00,
                'rate_peak_season' => 3100.00,
                'rate_shoulder_season' => 1400.00,
            ],
            [
                'name' => 'Sunset Overwater Pool Villa',
                'code' => 'x',
                'unit' => 11,
                'bedding' => '1 King',
                'extra_bed' => 0,
                'max_total_occupancy' => 3,
                'max_adult_occupancy' => 2,
                'max_child_occupancy' => 1,
                'base_rate_occupancy' => 2,
                'size' => 100.00,
                'rate_high_season' => 2175.00,
                'rate_low_season' => 1425.00,
                'rate_peak_season' => 3300.00,
                'rate_shoulder_season' => 1600.00,
            ],
            [
                'name' => 'Two Bedroom Overwater Pool Residence',
                'code' => 'x',
                'unit' => 2,
                'bedding' => '1 King, 2 Twin',
                'extra_bed' => 2,
                'max_total_occupancy' => 6,
                'max_adult_occupancy' => 6,
                'max_child_occupancy' => 5,
                'base_rate_occupancy' => 4,
                'size' => 295.00,
                'rate_high_season' => 8700.00,
                'rate_low_season' => 5850.00,
                'rate_peak_season' => 11000.00,
                'rate_shoulder_season' => 6225.00,
            ],
            [
                'name' => 'Three Bedroom Overwater Residence',
                'code' => 'x',
                'unit' => 1,
                'bedding' => '2 King, 2 Twin',
                'extra_bed' => 3,
                'max_total_occupancy' => 9,
                'max_adult_occupancy' => 9,
                'max_child_occupancy' => 8,
                'base_rate_occupancy' => 6,
                'size' => 460.00,
                'rate_high_season' => 12425.00,
                'rate_low_season' => 9075.00,
                'rate_peak_season' => 10300.00,
                'rate_shoulder_season' => 10300.00,
            ],
            [
                'name' => 'One Bedroom Lagoon Pool Villa',
                'code' => 'x',
                'unit' => 12,
                'bedding' => '1 King',
                'extra_bed' => 2,
                'max_total_occupancy' => 4,
                'max_adult_occupancy' => 3,
                'max_child_occupancy' => 2,
                'base_rate_occupancy' => 2,
                'size' => 150.00,
                'rate_high_season' => 2150.00,
                'rate_low_season' => 1300.00,
                'rate_peak_season' => 3500.00,
                'rate_shoulder_season' => 1475.00,
            ],
            [
                'name' => 'One Bedroom Sunset Lagoon Pool Villa',
                'code' => 'x',
                'unit' => 11,
                'bedding' => '1 King',
                'extra_bed' => 2,
                'max_total_occupancy' => 4,
                'max_adult_occupancy' => 3,
                'max_child_occupancy' => 2,
                'base_rate_occupancy' => 2,
                'size' => 150.00,
                'rate_high_season' => 2350.00,
                'rate_low_season' => 1500.00,
                'rate_peak_season' => 3700.00,
                'rate_shoulder_season' => 1675.00,
            ],
            [
                'name' => 'One Bedroom Sunset Lagoon Pool Villa',
                'code' => 'x',
                'unit' => 11,
                'bedding' => '1 King',
                'extra_bed' => 2,
                'max_total_occupancy' => 4,
                'max_adult_occupancy' => 3,
                'max_child_occupancy' => 2,
                'base_rate_occupancy' => 2,
                'size' => 150.00,
                'rate_high_season' => 2350.00,
                'rate_low_season' => 1500.00,
                'rate_peak_season' => 3700.00,
                'rate_shoulder_season' => 1675.00,
            ],
            [
                'name' => 'Two Bedroom Family Lagoon Pool Villa',
                'code' => 'x',
                'unit' => 2,
                'bedding' => '1 King, 1 Sofa Bed, 2 Twin',
                'extra_bed' => 2,
                'max_total_occupancy' => 6,
                'max_adult_occupancy' => 6,
                'max_child_occupancy' => 5,
                'base_rate_occupancy' => 4,
                'size' => 175.00,
                'rate_high_season' => 4450.00,
                'rate_low_season' => 2850.00,
                'rate_peak_season' => 5200.00,
                'rate_shoulder_season' => 3050.00,
            ],
            [
                'name' => 'Three Bedroom Lagoon Residence',
                'code' => 'x',
                'unit' => 1,
                'bedding' => '2 King, 2 Twin',
                'extra_bed' => 3,
                'max_total_occupancy' => 9,
                'max_adult_occupancy' => 9,
                'max_child_occupancy' => 8,
                'base_rate_occupancy' => 6,
                'size' => 610.00,
                'rate_high_season' => 11850.00,
                'rate_low_season' => 8425.00,
                'rate_peak_season' => 9500.00,
                'rate_shoulder_season' => 9500.00,
            ],
            [
                'name' => 'Beach Pool Villa',
                'code' => 'x',
                'unit' => 14,
                'bedding' => '1 King',
                'extra_bed' => 0,
                'max_total_occupancy' => 3,
                'max_adult_occupancy' => 2,
                'max_child_occupancy' => 1,
                'base_rate_occupancy' => 2,
                'size' => 145.00,
                'rate_high_season' => 2350.00,
                'rate_low_season' => 1360.00,
                'rate_peak_season' => 3600.00,
                'rate_shoulder_season' => 1575.00,
            ],
            [
                'name' => 'Family Beach Pool Villa',
                'code' => 'x',
                'unit' => 3,
                'bedding' => '1 King, 1 Sofa Bed',
                'extra_bed' => 0,
                'max_total_occupancy' => 4,
                'max_adult_occupancy' => 3,
                'max_child_occupancy' => 2,
                'base_rate_occupancy' => 2,
                'size' => 180.00,
                'rate_high_season' => 3050.00,
                'rate_low_season' => 1625.00,
                'rate_peak_season' => 4175.00,
                'rate_shoulder_season' => 1825.00,
            ],
            [
                'name' => 'One Bedroom Sunset Beach Pool Villa',
                'code' => 'x',
                'unit' => 9,
                'bedding' => '1 King',
                'extra_bed' => 2,
                'max_total_occupancy' => 4,
                'max_adult_occupancy' => 3,
                'max_child_occupancy' => 2,
                'base_rate_occupancy' => 2,
                'size' => 210.00,
                'rate_high_season' => 3900.00,
                'rate_low_season' => 2050.00,
                'rate_peak_season' => 4850.00,
                'rate_shoulder_season' => 2250.00,
            ],
            [
                'name' => 'Two Bedroom Family Beach Pool Villa',
                'code' => 'x',
                'unit' => 2,
                'bedding' => '1 King, 1 Sofa Bed, 2 Twin',
                'extra_bed' => 2,
                'max_total_occupancy' => 6,
                'max_adult_occupancy' => 6,
                'max_child_occupancy' => 5,
                'base_rate_occupancy' => 4,
                'size' => 275.00,
                'rate_high_season' => 5700.00,
                'rate_low_season' => 3450.00,
                'rate_peak_season' => 6750.00,
                'rate_shoulder_season' => 3650.00,
            ],
            [
                'name' => 'Two Bedroom Beachfront Pool Residence',
                'code' => 'x',
                'unit' => 2,
                'bedding' => '2 King, 2 Twin',
                'extra_bed' => 3,
                'max_total_occupancy' => 6,
                'max_adult_occupancy' => 6,
                'max_child_occupancy' => 5,
                'base_rate_occupancy' => 4,
                'size' => 535.00,
                'rate_high_season' => 10350.00,
                'rate_low_season' => 6500.00,
                'rate_peak_season' => 13050.00,
                'rate_shoulder_season' => 6925.00,
            ],
            [
                'name' => 'Three Bedroom Royal Beachfront Residence',
                'code' => 'x',
                'unit' => 1,
                'bedding' => '2 King, 2 Twin',
                'extra_bed' => 3,
                'max_total_occupancy' => 9,
                'max_adult_occupancy' => 9,
                'max_child_occupancy' => 8,
                'base_rate_occupancy' => 6,
                'size' => 1120.00,
                'rate_high_season' => 14850.00,
                'rate_low_season' => 10350.00,
                'rate_peak_season' => 12150.00,
                'rate_shoulder_season' => 12150.00,
            ],
        ];

        DB::table('rooms')->insert($rooms);
    }
}
